---
apiVersion: v1
kind: Service
metadata:
  name: openstack-exporter
  labels:
    app.kubernetes.io/name: openstack-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openstack-exporter
  ports:
    - name: metrics
      port: 9180
      targetPort: metrics
