apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-notepad
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notepad
  template:
    metadata:
      labels:
        app: notepad
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        