# ---------------------------------------------
# 예시 파일입니다. 실제 .pem 파일은 제 로컬에 있습니다.
# ---------------------------------------------

---
ansible_ssh_private_key_file: "/Users/YOUR_NAME/.ssh/YOUR_KEY.pem"
