---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-release
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: loki
      targetRevision: 6.6.0
      helm:
        valueFiles:
          - '$values/apps/log-server/values.yaml'
    - repoURL: 'https://github.com/TEAM-High-Cloud/Observability'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true