---
deploymentMode: SingleBinary

loki:
  auth_enabled: false

  limits_config:
    retention_period: 168h

  compactor:
    working_directory: /var/loki/compactor
    retention_enabled: true
    retention_delete_delay: 2h

minio:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0