---
deploymentMode: SingleBinary

loki:
  auth_enabled: false

  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin

  limits_config:
    retention_period: 168h

  compactor:
    working_directory: /var/loki/compactor
    retention_enabled: true
    retention_delete_delay: 2h
    delete_request_store: filesystem

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  storageConfig:
    filesystem:
      directory: /var/loki/chunks

minio:
  enabled: false

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumes:
    - name: data
      emptyDir: {}
  extraVolumeMounts:
    - name: data
      mountPath: /var/loki

chunksCache:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: loki-nodeport
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/component: single-binary
    spec:
      type: NodePort
      selector:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: single-binary
      ports:
        - name: http-metrics
          port: 3100
          targetPort: http-metrics
          nodePort: 31100
          protocol: TCP
