---
mode: daemonset

hostNetwork: true
dnsPolicy: Default

image:
  repository: otel/opentelemetry-collector-k8s

presets:
  hostMetrics:
    enabled: true
  kubeletMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
  logsCollection:
    enabled: true
    includeCollectorLogs: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

extraVolumes:
  - name: host-varlog
    hostPath:
      path: /var/log
      type: Directory

extraVolumeMounts:
  - name: host-varlog
    mountPath: /host/var/log
    readOnly: true

config:
  receivers:
    kubeletstats:
      endpoint: "https://127.0.0.1:10250"
    filelog/host:
      include:
        - /host/var/log/syslog
        - /host/var/log/auth.log
        - /host/var/log/openstack/**/*.log
        - /host/var/log/nova/**/*.log
        - /host/var/log/neutron/**/*.log
        - /host/var/log/cinder/**/*.log
        - /host/var/log/keystone/**/*.log
        - /host/var/log/glance/**/*.log
      start_at: end
      include_file_path: true
      include_file_name: false
      resource:
        log.source: host-varlog

  exporters:
    otlphttp/vm:
      metrics_endpoint: >-
        http://observ-metric-server:30428/opentelemetry/api/v1/push
      encoding: proto
    otlphttp/loki:
      logs_endpoint: http://observ-log-server:31100/otlp/v1/logs

  processors:
    batch: {}
    resourcedetection/system:
      detectors: [env, system]
      override: false
    resource/cluster:
      attributes:
        - key: k8s.cluster.name
          value: pc1
          action: upsert
    filter/drop_coredns_import_warning:
      error_mode: ignore
      logs:
        log_record:
          - 'IsMatch(body, ".*No files matching import glob pattern.*")'

  service:
    pipelines:
      metrics:
        receivers: [hostmetrics, kubeletstats]
        processors:
          - resourcedetection/system
          - resource/cluster
          - k8sattributes
          - batch
        exporters: [otlphttp/vm]
      logs:
        receivers: [filelog, filelog/host]
        processors:
          - resource/cluster
          - k8sattributes
          - filter/drop_coredns_import_warning
          - batch
        exporters: [otlphttp/loki]
