---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: alertmanager
      targetRevision: 1.11.0
      helm:
        releaseName: alertmanager
        valueFiles:
          - '$values/apps/metric-server/alertmanager/values.yaml'
    - repoURL: 'https://github.com/TEAM-High-Cloud/Observability'
      targetRevision: HEAD
      ref: values
  destination:
    name: metric
    namespace: alertmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
