---
replicaCount: 1
image:
  repository: 167781471242.dkr.ecr.ap-northeast-2.amazonaws.com/obs-ai-analyzer
  tag: "a052c2f"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  LOG_LEVEL: INFO
serviceAccount:
  create: true
  name: ai-analyzer
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
