---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-exporter-pc1-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/TEAM-High-Cloud/Observability'
    targetRevision: HEAD
    path: apps/openstack-finops/exporter-pc1/manifests
  destination:
    name: pc1
    namespace: openstack-finops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
