# ---------------------------------------------
# 예시 파일입니다. 실제 서버 주소가 노출되지 않게 주의하세용
# ---------------------------------------------

[argocd_server]
argocd ansible_host=YOUR_ARGOCD_SERVER_IP

[monitoring_servers]
metric ansible_host=YOUR_METRIC_SERVER_IP
log    ansible_host=YOUR_LOG_SERVER_IP
dashboard   ansible_host=YOUR_DASHBOARD_SERVER_IP

[onprem_pcs]
onprem-pc1   ansible_host=YOUR_PC1_IP
onprem-pc2   ansible_host=YOUR_PC2_IP

[all:vars]
ansible_user=ubuntu
